repo_name: Mimir Singleton Helm Charts
repo_url: https://github.com/intergral/mimir-singleton-helm

docs_dir: docs_out
site_dir: _site

site_name: Mimir Singleton Helm Charts
site_url: https://intergral.github.io/mimir-singleton-helm/

copyright: Intergral GmbH 2023

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

