{{- if not .Values.overrides.useExternalConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.overrides.externalRuntimeConfigName . }}
  labels:
    {{- include "mimir-singleton.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  overrides.yaml: |
    {{ include "mimir-singleton.overridesConfig" . | nindent 4 }}
{{- end }}