apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir-singleton.fullname" . }}
  labels:
    {{- include "mimir-singleton.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "mimir-singleton.serverHttpListenPort" . }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ include "mimir-singleton.serverGrpcListenPort" . }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "mimir-singleton.selectorLabels" . | nindent 4 }}
