name: Helm Lint

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - charts/**/*.*

env:
  CT_CONFIGFILE: ct.yaml

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Helm Lint
        run: |
          helm lint ${GITHUB_WORKSPACE}/charts/mimir-singleton

  helm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: helm plugin install https://github.com/helm-unittest/helm-unittest.git
      - name: Helm unittest
        run: |
          helm unittest -f unittests/*_test.yaml ${GITHUB_WORKSPACE}/charts/mimir-singleton

  helm-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --config "${CT_CONFIGFILE}")
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --config "${CT_CONFIGFILE}"

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.8.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --config "${CT_CONFIGFILE}" --debug
